overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat1.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0001
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0001 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0001.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat2.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0002
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0002 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0002.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat3.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0003
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0003 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0003.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat4.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0004
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0004 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0004.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat5.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0005
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0005 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0005.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat6.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0006
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0006 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0006.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat7.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0007
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0007 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0007.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat8.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0008
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0008 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0008.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat9.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0009
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0009 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0009.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat10.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0010
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0010 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0010.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat11.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0011
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0011 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0011.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat12.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0012
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0012 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0012.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat13.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0013
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0013 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0013.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat14.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0014
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0014 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0014.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat15.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0015
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0015 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0015.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat16.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0016
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0016 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0016.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat17.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0017
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0017 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0017.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat18.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0018
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0018 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0018.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat19.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0019
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0019 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0019.png
overlay 0 0 /corral-repl/utexas/poldracklab/software_lonestar/fsl-5.0.1/data/standard/MNI152_T1_2mm_brain.nii.gz -a  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ica_run2_20comp//stats/thresh_zstat20.nii.gz 2 6 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0020
slicer /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//rend0020 -S 5 100 /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0020.png
pngappend  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0001.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0002.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0003.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0004.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0005.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0006.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0007.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0008.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0009.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0010.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0011.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0012.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0013.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0014.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0015.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0016.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0017.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0018.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0019.png + /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//comp0020.png  /corral-repl/utexas/poldracklab/openfmri/analyses/paper_analysis_Dec2012/ICA/ICA_components_figure//all_comps.png
